/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.njangi;

import com.njangi.forms.AdminProfile;
import com.njangi.forms.ApproveLoan;
import com.njangi.forms.ApproveMember;
import com.njangi.forms.RecoverLoan;
import com.njangi.forms.RemoveMember;
import com.njangi.forms.UserProfile;
import com.njangi.models.Admin;
import java.awt.Color;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import com.njangi.statics.Path;

/**
 *
 * @author Admin
 */
public class AdminDashboard extends javax.swing.JFrame implements Path{

    private Admin njangiAdmin;
    /*Menu Items*/
    //Profile
    //Borrow
    //Contribute
    //View All members
    
    public AdminDashboard(Admin ad) {
        this.njangiAdmin = ad;
        initComponents();
        setBackground(new Color(0,0,0,0));
        init();
        initIcons();
    }
    
    private void setHome(){
        AdminProfile adProfile = new AdminProfile();
        adProfile.setData(njangiAdmin.getNjangiCode(), njangiAdmin.getMemberCount(), njangiAdmin.getNjangiName());
        setForm(adProfile);
    }
    
    private void setForm(JComponent com){
        pn_main.removeAll();
        pn_main.add(com);
        pn_main.repaint();
        pn_main.revalidate();
    }
    
    public final void init(){
        setBackground(new Color(0,0,0,0));
        initMenu();
        initIcons();
        initLogo();
        initHeader();
        setHome();
        
    }
    
    public void initHeader(){
        header1.setData(njangiAdmin.getNjangiName(), "Admin");
    }
    
    public final void initMenu(){
        lb_profile_text.setBackground(new Color(0,0,0,0));
        lb_profile.setBackground(new Color(0,0,0,0));
        lb_borrow_text.setBackground(new Color(0,0,0,0));
        lb_borrow.setBackground(new Color(0,0,0,0));
        lb_contribute_text.setBackground(new Color(0,0,0,0));
        lb_contribute.setBackground(new Color(0,0,0,0));
        lb_view_text.setBackground(new Color(0,0,0,0));
        lb_view.setBackground(new Color(0,0,0,0));
        lb_new.setBackground(new Color(0,0,0,0));
        lb_new_text.setBackground(new Color(0,0,0,0));
    }

    public final void initLogo(){
        ImageIcon ic = new ImageIcon(PREFIX+"money.png");
        Image scaledImg = ic.getImage().getScaledInstance(42,42,java.awt.Image.SCALE_SMOOTH);
        ic = new ImageIcon(scaledImg);
        lb_icon.setIcon(ic);
    }
   
    
    public final void initIcons(){        
        ImageIcon iProfile = new ImageIcon(PREFIX+"profile.png");
        iProfile = scaleIcon(iProfile);
        ImageIcon iBorrow = new ImageIcon(PREFIX+"approve.png");
        iBorrow = scaleIcon(iBorrow);
        ImageIcon iContribute = new ImageIcon(PREFIX+"recover.png");
        iContribute = scaleIcon(iContribute);
        ImageIcon iView = new ImageIcon(PREFIX+"member.png");
        iView = scaleIcon(iView);
        ImageIcon iNew = new ImageIcon(PREFIX+"remove.png");
        iNew = scaleIcon(iNew);
        
        lb_profile.setIcon(iProfile);
        lb_borrow.setIcon(iBorrow);
        lb_contribute.setIcon(iContribute);
        lb_view.setIcon(iView);
        lb_new.setIcon(iNew);
    }
    
    public final ImageIcon scaleIcon(ImageIcon i){
        Image sc = i.getImage().getScaledInstance(28, 28, java.awt.Image.SCALE_SMOOTH);
        ImageIcon ic = new ImageIcon(sc);
        return ic;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginBorder1 = new com.njangi.LoginBorder();
        sidebar1 = new com.njangi.extra.Sidebar();
        lb_icon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb_profile = new javax.swing.JLabel();
        lb_profile_text = new javax.swing.JLabel();
        lb_borrow_text = new javax.swing.JLabel();
        lb_borrow = new javax.swing.JLabel();
        lb_contribute_text = new javax.swing.JLabel();
        lb_contribute = new javax.swing.JLabel();
        lb_view_text = new javax.swing.JLabel();
        lb_view = new javax.swing.JLabel();
        lb_new_text = new javax.swing.JLabel();
        lb_new = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pn_main = new javax.swing.JPanel();
        header1 = new com.njangi.extra.Header();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        loginBorder1.setBackground(new java.awt.Color(255, 255, 255));

        lb_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NJANGI");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("[njangi-name]");

        lb_profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lb_profile_text.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lb_profile_text.setForeground(new java.awt.Color(255, 255, 255));
        lb_profile_text.setText("Profile");
        lb_profile_text.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_profile_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_profile_textMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_profile_textMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_profile_textMouseExited(evt);
            }
        });

        lb_borrow_text.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lb_borrow_text.setForeground(new java.awt.Color(255, 255, 255));
        lb_borrow_text.setText("Approve Loan");
        lb_borrow_text.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_borrow_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_borrow_textMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_borrow_textMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_borrow_textMouseExited(evt);
            }
        });

        lb_borrow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lb_contribute_text.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lb_contribute_text.setForeground(new java.awt.Color(255, 255, 255));
        lb_contribute_text.setText("Recover Loan");
        lb_contribute_text.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_contribute_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_contribute_textMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_contribute_textMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_contribute_textMouseExited(evt);
            }
        });

        lb_contribute.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lb_view_text.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lb_view_text.setForeground(new java.awt.Color(255, 255, 255));
        lb_view_text.setText("Approve Member");
        lb_view_text.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_view_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_view_textMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_view_textMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_view_textMouseExited(evt);
            }
        });

        lb_view.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lb_new_text.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lb_new_text.setForeground(new java.awt.Color(255, 255, 255));
        lb_new_text.setText("Remove Member");
        lb_new_text.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_new_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_new_textMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_new_textMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_new_textMouseExited(evt);
            }
        });

        lb_new.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout sidebar1Layout = new javax.swing.GroupLayout(sidebar1);
        sidebar1.setLayout(sidebar1Layout);
        sidebar1Layout.setHorizontalGroup(
            sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebar1Layout.createSequentialGroup()
                .addComponent(lb_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(sidebar1Layout.createSequentialGroup()
                .addGroup(sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_borrow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_contribute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidebar1Layout.createSequentialGroup()
                        .addGroup(sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_view, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_new, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_profile_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_contribute_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_borrow_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_view_text, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(lb_new_text, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidebar1Layout.setVerticalGroup(
            sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebar1Layout.createSequentialGroup()
                .addGroup(sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lb_icon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidebar1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_profile_text, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(lb_profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_borrow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_borrow_text, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_contribute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_contribute_text, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_view_text, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sidebar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_new, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_new_text, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(0, 271, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(94, 84, 142));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pn_main.setBackground(new java.awt.Color(255, 255, 255));
        pn_main.setMinimumSize(new java.awt.Dimension(701, 500));
        pn_main.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout loginBorder1Layout = new javax.swing.GroupLayout(loginBorder1);
        loginBorder1.setLayout(loginBorder1Layout);
        loginBorder1Layout.setHorizontalGroup(
            loginBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBorder1Layout.createSequentialGroup()
                .addComponent(sidebar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(loginBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginBorder1Layout.createSequentialGroup()
                        .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(pn_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        loginBorder1Layout.setVerticalGroup(
            loginBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(loginBorder1Layout.createSequentialGroup()
                .addGroup(loginBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lb_profile_textMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_profile_textMouseEntered
        // TODO add your handling code here:
        lb_profile_text.setOpaque(true);
        lb_profile.setOpaque(true);
        lb_profile_text.setBackground(Color.decode("#5E548E"));
        lb_profile.setBackground(Color.decode("#5E548E"));
        lb_profile.setBorder(BorderFactory.createMatteBorder(0, 6, 0, 0, Color.decode("#9E549D")));
    }//GEN-LAST:event_lb_profile_textMouseEntered

    private void lb_profile_textMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_profile_textMouseExited
        // TODO add your handling code here:
        lb_profile_text.setOpaque(false);
        lb_profile.setOpaque(false);
        initMenu();
        lb_profile_text.setBackground(new Color(0,0,0,0));
        lb_profile.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lb_profile_textMouseExited

    private void lb_borrow_textMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_borrow_textMouseEntered
        // TODO add your handling code here:
        lb_borrow_text.setOpaque(true);
        lb_borrow.setOpaque(true);
        lb_borrow_text.setBackground(Color.decode("#5E548E"));
        lb_borrow.setBackground(Color.decode("#5E548E"));
        lb_borrow.setBorder(BorderFactory.createMatteBorder(0, 6, 0, 0, Color.decode("#9E549D")));
    }//GEN-LAST:event_lb_borrow_textMouseEntered

    private void lb_borrow_textMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_borrow_textMouseExited
        // TODO add your handling code here:
        lb_borrow_text.setOpaque(false);
        lb_borrow.setOpaque(false);
        initMenu();
        lb_borrow_text.setBackground(new Color(0,0,0,0));
        lb_borrow.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lb_borrow_textMouseExited

    private void lb_contribute_textMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_contribute_textMouseEntered
        // TODO add your handling code here:
        lb_contribute_text.setOpaque(true);
        lb_contribute.setOpaque(true);
        lb_contribute_text.setBackground(Color.decode("#5E548E"));
        lb_contribute.setBackground(Color.decode("#5E548E"));
        lb_contribute.setBorder(BorderFactory.createMatteBorder(0, 6, 0, 0, Color.decode("#9E549D")));
    }//GEN-LAST:event_lb_contribute_textMouseEntered

    private void lb_contribute_textMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_contribute_textMouseExited
        // TODO add your handling code here:
        lb_contribute_text.setOpaque(false);
        lb_contribute.setOpaque(false);
        initMenu();
        lb_contribute_text.setBackground(new Color(0,0,0,0));
        lb_contribute.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lb_contribute_textMouseExited

    private void lb_view_textMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_view_textMouseEntered
        // TODO add your handling code here:
        lb_view_text.setOpaque(true);
        lb_view.setOpaque(true);
        lb_view_text.setBackground(Color.decode("#5E548E"));
        lb_view.setBackground(Color.decode("#5E548E"));
        lb_view.setBorder(BorderFactory.createMatteBorder(0, 6, 0, 0, Color.decode("#9E549D")));
    }//GEN-LAST:event_lb_view_textMouseEntered

    private void lb_view_textMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_view_textMouseExited
        // TODO add your handling code here:
        lb_view_text.setOpaque(false);
        lb_view.setOpaque(false);
        initMenu();
        lb_view_text.setBackground(new Color(0,0,0,0));
        lb_view.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lb_view_textMouseExited

    private void lb_profile_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_profile_textMouseClicked
        // TODO add your handling code here:
        setHome();
    }//GEN-LAST:event_lb_profile_textMouseClicked

    private void lb_borrow_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_borrow_textMouseClicked
        // TODO add your handling code here:
        ApproveLoan b_form = new ApproveLoan(njangiAdmin);
        setForm(b_form);
    }//GEN-LAST:event_lb_borrow_textMouseClicked

    private void lb_contribute_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_contribute_textMouseClicked
        // TODO add your handling code here:
        RecoverLoan c_form = new RecoverLoan(njangiAdmin);
        setForm(c_form);
    }//GEN-LAST:event_lb_contribute_textMouseClicked

    private void lb_view_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_view_textMouseClicked
        // TODO add your handling code here:
        ApproveMember v_form = new ApproveMember(njangiAdmin);
        setForm(v_form);
    }//GEN-LAST:event_lb_view_textMouseClicked

    private void lb_new_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_new_textMouseClicked
        // TODO add your handling code here:
        RemoveMember r_form = new RemoveMember(njangiAdmin);
        setForm(r_form);
        
    }//GEN-LAST:event_lb_new_textMouseClicked

    private void lb_new_textMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_new_textMouseEntered
        // TODO add your handling code here:
        lb_new_text.setOpaque(true);
        lb_new.setOpaque(true);
        lb_new_text.setBackground(Color.decode("#5E548E"));
        lb_new.setBackground(Color.decode("#5E548E"));
        lb_new.setBorder(BorderFactory.createMatteBorder(0, 6, 0, 0, Color.decode("#9E549D")));
    }//GEN-LAST:event_lb_new_textMouseEntered

    private void lb_new_textMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_new_textMouseExited
        // TODO add your handling code here:
        lb_new_text.setOpaque(false);
        lb_new.setOpaque(false);
        initMenu();
        lb_new_text.setBackground(new Color(0,0,0,0));
        lb_new.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lb_new_textMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.njangi.extra.Header header1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lb_borrow;
    private javax.swing.JLabel lb_borrow_text;
    private javax.swing.JLabel lb_contribute;
    private javax.swing.JLabel lb_contribute_text;
    private javax.swing.JLabel lb_icon;
    private javax.swing.JLabel lb_new;
    private javax.swing.JLabel lb_new_text;
    private javax.swing.JLabel lb_profile;
    private javax.swing.JLabel lb_profile_text;
    private javax.swing.JLabel lb_view;
    private javax.swing.JLabel lb_view_text;
    private com.njangi.LoginBorder loginBorder1;
    private javax.swing.JPanel pn_main;
    private com.njangi.extra.Sidebar sidebar1;
    // End of variables declaration//GEN-END:variables
}
